### ISSUE TITLE
Use my new nginx action to set up nginx in CI

### ISSUE THREAD

**Issue by nyurik** [stadiamaps/pmtiles-rs#41]
I think it will be a good fit for http testing:  https://github.com/nyurik/action-setup-nginx

```yaml
      - name: Run NGINX
        uses: nyurik/action-setup-nginx@v1.1
        id: nginx
        with: { port: '5412', output-unix-paths: 'yes' }

      - name: Copy static files
        run: cp -r tests/fixtures/* ${{ steps.nginx.outputs.html-dir }}

      - name: Test pmtiles
        run: |
          # Some code that runs web-serving
```
